# Generated by Django 5.1.2 on 2024-10-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversionhistory',
            old_name='timestamp',
            new_name='conversion_date',
        ),
        migrations.RemoveField(
            model_name='conversionhistory',
            name='conversion_rate',
        ),
        migrations.AlterField(
            model_name='conversionhistory',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='conversionhistory',
            name='converted_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='conversionhistory',
            name='from_currency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='conversionhistory',
            name='to_currency',
            field=models.CharField(max_length=3),
        ),
    ]
